M48
; DRILL file {KiCad 7.0.5} date Sat Sep 14 15:13:58 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-14T15:13:58-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X5.0453Y-2.4745
X5.0453Y-2.8288
T2
X3.7205Y-1.8307
X3.7205Y-4.8425
X8.8287Y-4.8425
X8.8386Y-1.8307
T0
M30
